import { AiFillStar } from "react-icons/ai";

const data = [
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Retro-High-OG-Yellow-Toe/Images/Air-Jordan-1-Retro-High-OG-Yellow-Toe/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1659075277&h=384&q=60",
        title: "Jordan 1 Retro High OG Taxi",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 1",
        color: "yellow",
        category: "High",
        id: 1,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-High-OG-UNC-Toe/Images/Air-Jordan-1-High-OG-UNC-Toe/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1688674754&h=384&q=60",
        title: "Jordan 1 Retro High OG UNC Toe",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 1",
        color: "blue",
        category: "High",
        id: 2,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Low-Alternate-Bred-Toe/Images/Air-Jordan-1-Low-Alternate-Bred-Toe/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1681374247&h=384&q=60",
        title: "Jordan 1 Low Alternate Bred Toe",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Jordan 1",
        color: "red",
        category: "Low",
        id: 3,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Low-Navy-Royal-W/Images/Air-Jordan-1-Low-Navy-Royal-W/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1647447157&h=384&q=60",
        title: "Jordan 1 Low Game Royal Blue Void",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Jordan 1",
        color: "blue",
        category: "Low",
        id: 4,
    },
    {
        img: "https://images.stockx.com/360/Nike-Dunk-Low-Black-White-2021/Images/Nike-Dunk-Low-Black-White-2021/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1645006140&h=384&q=60",
        title: "Nike Dunk High Panda Black White",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Dunk",
        color: "black",
        category: "High",
        id: 5,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-5-Retro-UNC-University-Blue/Images/Air-Jordan-5-Retro-UNC-University-Blue/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1678267312&h=384&q=60",
        title: "Jordan 5 Retro UNC University Blue",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 5",
        color: "blue",
        category: "High",
        id: 6,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-3-Retro-Wizards/Images/Air-Jordan-3-Retro-Wizards/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1682522715&h=384&q=60",
        title: "Jordan 3 Retro Wizards",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$150,00",
        newPrice: "$150",
        company: "Jordan 3",
        color: "white",
        category: "High",
        id: 7,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-4-Retro-Thunder-2023-GS/Images/Air-Jordan-4-Retro-Thunder-2023-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1682522704&h=384&q=60",
        title: "Jordan 4 Retro Thunder",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 4",
        color: "black",
        category: "High",
        id: 8,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-4-Retro-Military-Black/Images/Air-Jordan-4-Retro-Military-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1652820880&h=384&q=60",
        title: "Jordan 4 Retro Military Black",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 4",
        color: "white",
        category: "High",
        id: 9,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-4-Retro-Taupe-Haze/Images/Air-Jordan-4-Retro-Taupe-Haze/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635261209&h=384&q=60",
        title: "Jordan 4 Retro Taupe Haze",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 4",
        color: "purple",
        category: "High",
        id: 10,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-4-Retro-University-Blue/Images/Air-Jordan-4-Retro-University-Blue/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635344971&h=384&q=60",
        title: "Jordan 4 Retro University Blue",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 4",
        color: "blue",
        category: "High",
        id: 11,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-4-Retro-Lightning-2021-GS/Images/Air-Jordan-4-Retro-Lightning-2021-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635278768&h=384&q=60",
        title: "Jordan 4 Retro Lightning",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 4",
        color: "yellow",
        category: "High",
        id: 12,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Retro-High-OG-Lucky-Green/Images/Air-Jordan-1-Retro-High-OG-Lucky-Green/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1681154580&h=384&q=60",
        title: "Jordan 1 Retro High OG Lucky Green",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 1",
        color: "green",
        category: "High",
        id: 13,
    },
    {
        img: "https://images.stockx.com/360/Nike-Dunk-Low-Retro-White-Black-GS/Images/Nike-Dunk-Low-Retro-White-Black-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635187072&h=384&q=60",
        title: "Nike Dunk Low Retro White Black Panda",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Dunk",
        color: "black",
        category: "Low",
        id: 14,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Retro-High-OG-Chicago-Reimagined/Images/Air-Jordan-1-Retro-High-OG-Chicago-Reimagined/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1665692308&h=384&q=60",
        title: "Jordan 1 Retro High OG Chicago Lost And Found",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 1",
        color: "red",
        category: "High",
        id: 15,
    },
    {
        img: "https://images.stockx.com/360/adidas-Yeezy-Slide-Black/Images/adidas-Yeezy-Slide-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1646687558&h=384&q=60",
        title: "Adidas Yeezy Slide Onyx",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Yeezy",
        color: "black",
        category: "Slide",
        id: 16,
    },
    {
        img: "https://images.stockx.com/360/adidas-Yeezy-Slide-Azure/Images/adidas-Yeezy-Slide-Azure/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1670430119&h=384&q=60",
        title: "Adidas Yeezy Slide Azure",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Yeezy",
        color: "blue",
        category: "Slide",
        id: 17,
    },
    {
        img: "https://images.stockx.com/360/adidas-Yeezy-Foam-RNNR-MX-Brown-Blue/Images/adidas-Yeezy-Foam-RNNR-MX-Brown-Blue/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1686137075&h=384&q=60",
        title: "Adidas Yeezy Foam RNR MX Cinder",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Yeezy",
        color: "brown",
        category: "Slide",
        id: 18,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Low-fragment-design-x-Travis-Scott/Images/Air-Jordan-1-Low-fragment-design-x-Travis-Scott/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635183978&h=384&q=60",
        title: "Jordan 1 Retro Low OG SP Fragment X Travis Scott",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 1",
        color: "white",
        category: "Low",
        id: 19,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Retro-Low-Travis-Scott/Images/Air-Jordan-1-Retro-Low-Travis-Scott/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1634915513&h=384&q=60",
        title: "Jordan 1 Retro Low OG SP Travis Scott Mocha",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$200",
        company: "Jordan 1",
        color: "black",
        category: "Low",
        id: 20,
    },
    {
        img: "https://images.stockx.com/360/Nike-Dunk-Low-6-0-Delorean-DMC-12/Images/Nike-Dunk-Low-6-0-Delorean-DMC-12/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635276299&h=384&q=60",
        title: "Nike Dunk Low 6.0 SE Delorean DMC-12",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Dunk",
        color: "silver",
        category: "Low",
        id: 21,
    },
    {
        img: "https://images.stockx.com/images/Nike-Dunk-High-Vintage-Pine-Green.png?fit=fill&bg=FFFFFF&w=576&h=384&fm=avif&auto=compress&dpr=2&trim=color&updated_at=1609945533&q=60",
        title: "Nike Dunk High Vintage Pine Green",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Dunk",
        color: "green",
        category: "High",
        id: 22,
    },
    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Retro-High-OG-Gorge-Green-White-GS/Images/Air-Jordan-1-Retro-High-OG-Gorge-Green-White-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1686172897&h=384&q=60",
        title: "Jordan 1 Retro High OG Gorge Green ",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$150",
        company: "Jordan 1",
        color: "green",
        category: "High",
        id: 23,
    },

    {
        img: "https://images.stockx.com/360/Air-Jordan-1-Low-Black-White-Grey/Images/Air-Jordan-1-Low-Black-White-Grey/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1635615900&h=384&q=60",
        title: "Jordan 1 Low Black White Grey",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Jordan 1",
        color: "black",
        category: "Low",
        id: 24,
    },
    {
        img: "https://images.stockx.com/360/Nike-Dunk-Low-Next-Nature-Light-Curry-W/Images/Nike-Dunk-Low-Next-Nature-Light-Curry-W/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1663784718&h=384&q=60",
        title: "Nike Dunk Low Next Nature Phantom Gold Suede",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Dunk",
        color: "yellow",
        category: "Low",
        id: 25,
    },
    {
        img: "https://images.stockx.com/360/Nike-Dunk-Low-Next-Nature-White-Gym-Red-W/Images/Nike-Dunk-Low-Next-Nature-White-Gym-Red-W/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=2&updated_at=1644487687&h=384&q=60",
        title: "Nike Dunk Low Next Nature White Gym Red",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "$100",
        company: "Dunk",
        color: "red",
        category: "Low",
        id: 26,
    },
];

export default data;